### ISSUE TITLE
Increase/decrease buttons stop responding

### ISSUE THREAD

**Issue by nroutasuo** [nroutasuo/level13#10]
Description from @JayL1F3 on #7 

Occasionally clicking an arrow will cause no feedback. Number does not increase or decrease. Reload is necessary.

**Comment by Pimhazeveld** [comment]
a reliable way to stop buttons from responding is moving to a different camp and trying to assign workers.

**Comment by praxiq** [comment]
Steps to reproduce this problem consistently:

1. Assign workers to tasks until there is one free worker. Assign this last worker to any task - let's say, "trapper." (Or, if all workers are already assigned, try to assign one more to trapper.) This will disable the trapper plus button. (In the dev tools, the attribute `disabled="disabled"` gets added to the button).
2. Remove a worker from any task *other than trapper,* so you have a free worker again. The trapper "+" button, disabled in step 1, will incorrectly remain disabled.
3. Try to assign this worker to "trapper." It won't work.
4. To fix, remove a worker from "trapper." This will "unlock" the "+" button so you can add more trappers again.
5. If the trapper "+" button is disabled when you have no trappers assigned, then you can't remove a trapper, and the only way to recover is to reload the page. (You can get into this state by clicking the "+" button when you have no trappers, and no free workers to assign.)

**Comment by livinginformation** [comment]
I've looked the code over a little, and a 'fix' could be done by adding a function that triggers every time the number of free workers changes, that re-evaluates the state of the stepper buttons.

I may implement this myself, shouldn't be too hard.

**Comment by ivangift** [comment]
Or making things simpler, just remove the logic of setting disabled. This is only a nice-to-have feature, even if button is not disabled, clicking on it will not bring in any problems.

**Comment by nroutasuo** [comment]
This should finally be fixes on master and the fix will be in the next update. Thank you for the detailed reproduction steps!
