### ISSUE TITLE
Trading caravans exceed capacity

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#100]
**Game version**
v 0.2.3 (alpha)

**Browser**
Mozilla Firefox

**Description**
When trading using caravans the capacity is not respected. The trade screen correctly states the amount I should get in return(i.e. 10 rope to 100 metal or 80 rope for 750 metal), however trades that should get capped by capacity are not, i.e. a caravan with 120 rope returns with 1200 metal.

**Comment by nroutasuo** [comment]
Fixed for the upcoming release.
