### ISSUE TITLE
Losing fight before first camp is established

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#101]
**Game version**
v 0.2.3 (alpha)

**Browser**
Mozilla Firefox

**Description**
In my first attempt at this version I ended up in a fight before establishing my first camp. I predictably lost, however the button to move on did not work, which effectively softlocked the game.

**Comment by Tobiyashi** [comment]
i have the same bug.
console log:
TypeError: this.lastVisitedCampNodes.head is null              FaintingSystem.js:156:4
fadeOutToLastVisitedCamp  |   https://nroutasuo.github.io/level13/src/game/systems/FaintingSystem.js:156
endFight   |   https://nroutasuo.github.io/level13/src/game/helpers/FightHelper.js:114
registerActionButtonListeners  |   https://nroutasuo.github.io/level13/src/game/UIFunctions.js:206

**Comment by nroutasuo** [comment]
Thanks for the console log! I'll get this one fixed asap.

**Comment by nroutasuo** [comment]
Should be fixed in the next update. Also blocked you from getting any fights before first camp.
