### ISSUE TITLE
water towers and buckets

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#103]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
While at a water tower I tried to create a trap and by doing so the option for building a bucket suddenly appeared as I made the trap. This option disappeared as I left the water tower.

**Comment by Karthas077** [comment]
At almost every water tower (or any place with the "Refill Water" option) I get an option to build (or loot from) a bucket, but only if it's the very first thing I do when entering that sector.

**Comment by nroutasuo** [comment]
Fixed for the next update. Thanks for reporting!
