### ISSUE TITLE
Game thinks my bag is full which it isn't

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#104]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
I had 16/30 spaces taken. I tried to collect water from a bucket but couldn't because my inventory was apparantly full. Here's a picture https://i.imgur.com/ePFnFa0.png

**Comment by Pimhazeveld** [comment]
> I've run into this problem a few times now. Switching to the bag screen and then bag appears to recalculate whether or not the button should be enabled.

Right now you can solve it by doing something that involves your inventory. Looting something, refreshing the game. All reset the button so you can use it again.

**Comment by nroutasuo** [comment]
The upcoming version will have a lot of improvements to how and when the UI refreshes and this bug should also be fixed. Let me know if you encounter any issues in the new version (once it's released).
