### ISSUE TITLE
Despair. Game didn't tell me I got injured.

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#105]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
I pressed the despair button to get back to camp. The game didn't tell me I got injured but I got a broken rib a second after entering camp.

**Comment by nroutasuo** [comment]
I haven't been able to reproduce this one, and it's quite old, so I am closing the ticket. Hopefully it no longer occurs in the latest version.
