### ISSUE TITLE
Food is EVERYWHERE

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#106]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
Just look at my map. Every single tile contains food. https://i.imgur.com/ioKM6PE.png

**Comment by iuriguilherme** [comment]
World seed **4658** looks like that too. (v0.2.7)

**Comment by nroutasuo** [comment]
I've adjusted world generation quite a bit for the upcoming version and this should also be fixed then, so closing this issue for now.
