### ISSUE TITLE
You can still overburden yourself by looting enemies

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#108]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
When you defeat an enemy and loot items, you can loot more than you can carry and it doesn't gray out the continue button. The game never checks for if you're carrying too much and just lets you have it. I tried this on a group of enemies. Here's the aftermath https://i.imgur.com/e4jBYtv.png

**Comment by nroutasuo** [comment]
Fixed in the upcoming version.
