### ISSUE TITLE
Injuries disguised as different debuffs

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#109]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
I despaired due to my hunger hitting 0. When I reached camp I was greeted by this https://i.imgur.com/WTpRz6I.png . A minor injury disguised as the hunger debuff. The debuff looking like hunger is the only thing that's abnormal. It still behaves like an injury including being able to be cured.

**Comment by nroutasuo** [comment]
This should be fixed in the upcoming version.
