### ISSUE TITLE
Running out of energy before building a camp

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#110]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
Its possible to run out of energy by scavenging before building a camp. If you don't have enough resources its impossible to build your first camp and you'll have to restart.

**Comment by KelvinCrank22** [comment]
Should probably just set the scavenge probability & light level regen to be much higher before you set up a camp

**Comment by nroutasuo** [comment]
Fixed by fixing the rest outside option not being visible when you run out of stamina before the first camp.
