### ISSUE TITLE
Got put right outside the camp after despair

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#112]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
After despairing on floor 11 I got put back outside camp 12. I only had access to my own inventory but the camp screen was loaded by default so I could change workers positions while not being in camp. I could also rest which resulted in [strange circumstances,](https://i.imgur.com/3fugHlQ.png) house and campfire and I lost access to all actions inside the camp after going to the map screen.

**Comment by desci** [comment]
https://imgur.com/a/AxMTnl7

**Comment by nroutasuo** [comment]
I haven't been able to reproduce this one, and it's quite old, so I am closing the ticket. Hopefully it no longer occurs in the latest version.
