### ISSUE TITLE
Equipping weapon during travel made it invisible

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#113]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
I was adventuring without any weapons. I happened to carry a shiv on me and equipped it. The shiv did not disappear, did not go into my weapon slot but my damage did increase, It's like there's a second invisible shiv in my hand slot now. Here's a [picture](https://i.imgur.com/aIdOz8j.png) of the situation

**Comment by nroutasuo** [comment]
Fixed this (and a few related issues I found while looking into this) for the next update. Thanks!
