### ISSUE TITLE
recruited 1 person, got 5

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#114]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
After disbanding my 5 attack guy and hiting a 6 attack guy instead. I look at my party menu to suddenly find a group of 5 6 attack guys there. Here's a [picture](https://i.imgur.com/tLiJhD9.png)

**Comment by JL421** [comment]
Same version, same bug, same browser.

Action: Disband party, click recruit for one member.
Result: Recruited 27 party members.
Expected: Recruit one party member.

Additional Info:
All party members recruited have the same attack buff. I doubt the level had any influence, but this occurred on level 8. It appears that the recruit function kept adding party members until I ran out of food and water to recruit any additional members.

**Comment by livinginformation** [comment]
Same happened to me - ended up with 14 party members.
