### ISSUE TITLE
Reputation needs some rounding

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#115]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
Reputation cap is 12.8999999 after building some buildings I assume this is caused by the "bad defense" debuff. [Here's](https://i.imgur.com/j8xXfx8.png) my setup. (1 caravan, 0 block)

**Comment by nroutasuo** [comment]
Nice catch, should be fixed in the next update.
