### ISSUE TITLE
No camp on level 6?

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#116]
**Game version**
0.2.3

**Browser**
Chrome

**Description**
I explored the entirety of level 6 but there's no camp there. Here is a [picture](https://i.imgur.com/I29ykHU.png). My world seed is 4782

**Comment by nroutasuo** [comment]
Could you share the save as well?

**Comment by Pimhazeveld** [comment]
> Could you share the save as well?

Here https://pastebin.com/mBbHyyvX

**Comment by Pimhazeveld** [comment]
> Could you share the save as well?

If possible. Could you also fix the save for me by placing the missing camp spots? Right now I'm kinda stuck and can't progress but I wanna see some more stuff in deeper floors.

**Comment by nroutasuo** [comment]
Thanks! I'm hoping to release some bugfixes to this version soon so if this turns out to be a simple fix it'll hopefully fix existing saves as well. If not.. it might take longer than is worth waiting for.

**Comment by nroutasuo** [comment]
I've found the problem and it's a silly little mistake so you should be able to continue this save as soon as I release the next update.

**Comment by livinginformation** [comment]
I believe I don't have a camp either, I'm near finished exploring all of floor 6. Not totally though, so I've been holding out hope (but it's been hard without a camp, with the reduced stamina. I've been forced to exhaust to explore)
