### ISSUE TITLE
crafting menu is hides obsolete items even with marked checkbox

### ISSUE THREAD

**Issue by Tobiyashi** [nroutasuo/level13#117]
**Game version**
0.2.3 (alpha)

**Browser**
Firefox 66.0.2

**Description**
The crafting menu doesn't recognize the "Show obsolete" checkbox after reloading the game.

I let the checkbox always on. When i save and reload the page the crafting menu always shows only the lock pick. I have to deactivate and activate the checkbox again to show all craftable items.
![level13_bug](https://user-images.githubusercontent.com/49440579/55957149-dd8d7b80-5c65-11e9-9d58-a9bf3226b951.PNG)

**Comment by nroutasuo** [comment]
This was interesting, I mainly use Chrome and it doesn't save the checkbox status this way, so I would never have noticed the bug myself. Thank you for reporting. Finally fixed for the upcoming version.
