### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by livinginformation** [nroutasuo/level13#118]
**Game version**

v0.2.3

**Browser**

Firefox

**Description**

Typos

Wollen Hat -> Woolen Hat

Artefact -> Artifact (unless you intended it?)

Will update if I find more.

**Comment by nroutasuo** [comment]
I actually thought it was "wollen"! I need to have a native English speaker proof-read this game at some point. I'll fix these though. Thank you!

**Comment by livinginformation** [comment]
I am a native english speaker (and programmer), and am working my way through your game for the third reset. I love (and have loved since I found it) the direction you're going, and will happily point out spelling/grammar issues as I encounter them.

**Comment by livinginformation** [comment]
@nroutasuo 

So, "Woolen Hat" should really be "Wool Hat". 

Lock Pick should be Lockpick (the word carries it's own meaning, it isn't two separate words).

Basic First Aid Kit capitalizes all words in the item, whereas the other items I've seen only capitalize the first word

Factory Uniform Pants description has "univorm" in it

will continue to add as typos are seen.

**Comment by nroutasuo** [comment]
Thank you! By all means keep posting them here or make a pull request if you find more. Are you from the US? I checked Artefact vs Artifact and according to Google Artefact is more common in British English. Being European myself when in doubt I tend to favour British.

**Comment by livinginformation** [comment]
So, while Artefact is a british english spelling of artifact, as far as I'm aware, artifact is in much more common use (even in Britain). Artefact as far as I'm aware is a fairly uncommon useage.
