### ISSUE TITLE
Only take whole numbers

### ISSUE THREAD

**Issue by livinginformation** [nroutasuo/level13#119]
**Game version**
v0.2.3

**Description**
When taking stuff from traps/buckets, only decrement by integers. Will fix the partial balance issues.

**Comment by Tobiyashi** [comment]
Yes Please!
And it would be nice to have the possibility to take a set number of water/food and not everything.

**Comment by nroutasuo** [comment]
Good idea, the resource parts made sense earlier but don't really in the current game. Fixed for the next update. As for the custom collection amounts, there is already a ticket for that: #8
