### ISSUE TITLE
Cooldown bars are not refreshed.

### ISSUE THREAD

**Issue by SaphireLattice** [nroutasuo/level13#120]
**Game version**
v. 0.2.3 (alpha)

**Browser**
Firefox Developer Edition - 67.0b8 (64-bit)

**Description**
Cooldown bars are not refreshed in real time.

Instead they are only refreshed when the button is fully "ready" or gets used, or on switching tabs and other means of recreating the UI.

**Comment by nroutasuo** [comment]
This was fixed recently and will be included in the next update. Thanks for reporting!
