### ISSUE TITLE
Disappearing Clinics

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#121]
**Game version**
v. 0.2.4

**Browser**
Mozilla Firefox

**Description**
Upon loading my save in the new version I noticed I didn't have a clinic in my level 8 camp. I rebuilt it and checked the other camps, and, at the time, only my level 10 camp was the only other camp to lack one. However it did not stop there and, as I kept playing, my clinics kept disappearing.

**Comment by nroutasuo** [comment]
Do clinics you built after the update disappear also? As you might have seen on Reddit the update unfortunately does lose old clinics but it shouldn't affect further gameplay.

**Comment by mavion** [comment]
I thought it happened afterwards, but there's been a good period where it hasn't, so I probably just didn't pay enough attention when it initially happened.

**Comment by Pimhazeveld** [comment]
I have the same issue. I had clinics in all my camps but they disappeared.

**Comment by mavion** [comment]
I haven't had any repeats since then, so I'm leaning towards my initial belief of "it happened some time after login" was just a lack of attention.

**Comment by nroutasuo** [comment]
Closing since this hasn't appeared since.
