### ISSUE TITLE
Camps on level 6 ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#122]
**Game version**
0.2.4

**Browser**
Chrome

**Description**
[This is getting out of hand. Now there's 2 of them](https://i.imgur.com/ry9R73p.png)
(please forgive me if this is not a bug and building a camp on 2 different spots is intended)

**Comment by mavion** [comment]
All campable levels have, as far as I've seen, two campable spots. You can however only pick one of them, the other will disappear when the first is settled.

**Comment by nroutasuo** [comment]
Yes, as @mavion said this is not a bug. :)
