### ISSUE TITLE
Tools do not appear in the top bar.

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#128]
**Game version**
v. 0.2.4

**Browser**
Mozilla Firefox

**Description**
Toolsmiths produce tools, these tools do not appear in the top bar unlike the other resources, but it does appear in the other expected places, i.e. the contribution to production is visible in the tribe tab of the camp and it can be moved as a resource in the outside tab.
I haven't seen any use for them yet, but I assume that's just unimplemented content.

As a possible related issue. Unlocking Metalworking 1 had the indicator icon appear with the number two over the bag, but the only new item was the crossbow.

**Comment by Pimhazeveld** [comment]
I had this issue too at first. But I wasn't looking closely enough. now it [shows up for me](https://i.imgur.com/7vlVwEd.png)

**Comment by mavion** [comment]
http://prntscr.com/nbt6o5
There's nothing in that space for me, not even after refreshing.

**Comment by Brilliand** [comment]
I had it missing for a while, but eventually it showed up.  Something not being updated immediately, I guess?

I may have triggered it to show up by bringing tools into my camp some other way.

**Comment by nroutasuo** [comment]
Finally fixed this one. The trigger for them to show up was to scavenge or collect from traps/buckets, forcing a proper resources update. In the upcoming version new resources will show up immediately.
