### ISSUE TITLE
Game thinks Improvised flip-flops are better than Worn trainers

### ISSUE THREAD

**Issue by Brilliand** [nroutasuo/level13#130]
**Game version**
0.2.4

**Browser**
Chrome 72.0.3626.121

**Description**
I just found the Worn trainers when scavenging, and promptly equipped them.  Now the game keeps notifying me about my old Improvised flip-flops, as though they're an upgrade over the Worn trainers.

**Comment by Pimhazeveld** [comment]
Oh I actually posted this error way back when the game was in an older state. Guess he didnt fix it.
