### ISSUE TITLE
Allow deconstructing buildings

### ISSUE THREAD

**Issue by Brilliand** [nroutasuo/level13#133]
**Game version**
0.2.4

**Description**
I recently figured out that raid threat is based on number of buildings built, and reputation penalty is based on raid threat.  I have a number of useless Smithies built in most of my camps (one per camp would have been enough), and I've already built the maximum amount of Fortifications for my camps (given my storage size), so I'd like to deconstruct my Smithies to squeeze some extra reputation out of my camps.

**Comment by Brilliand** [comment]
While the defense-smithy interaction is awkward, I'm not sure that deconstructing buildings is a good fit for this game.  It might be better to relieve the pressure in a different way, i.e. by making the raid threat (and thus the poor defense penalty) depend on reputation from buildings instead of on building count.  (This is how I thought it worked originally, before I looked at the source code.)

**Comment by nroutasuo** [comment]
I've been going back and forth on the idea of deconstructing buildings myself, I think it on some very early version even existed. But given that the idea of reputation is to force you to balance the kind of buildings you build, deconstructing would make sense.

**Comment by Centritide** [comment]
If not deconstructing, maybe you could allow abandoning a building? I don't know about the details but maybe reclaiming the building could be at a lower cost than constructing it

**Comment by nroutasuo** [comment]
Deconstructing buildings has been finally added in the upcoming version so closing this issue.
