### ISSUE TITLE
Textbox for trading

### ISSUE THREAD

**Issue by desci** [nroutasuo/level13#134]
**Game version**
0.2.4

**Description**
Change the trading system to something similar to the resource allocation for exploring or the workers assignment.
I had to write a macro to click 400 times when trying to trade fuel, metal, rope, food, water, etc. otherwise I would break both the mouse and my finger.
I'm confident people don't even bother to trade something that exceeds 10 items.

**Comment by mavion** [comment]
There should be an option to the bottom right for selecting multiples of 1, 10, 100

**Comment by nroutasuo** [comment]
@desci , did you not notice the multiple selection button (in which case I should probably make it more obvious) or did it bug out for you somehow?

**Comment by desci** [comment]
If it's on >0.2.3, I'll ave to get to trading to check it out. I definitely missed if it was on 0.2.2

**Comment by nroutasuo** [comment]
It's new on 0.2.3 and you reported the issue for 0.2.4. Closing this for now, let me know if you have problems on the latest version.

**Comment by desci** [comment]
Found it and it's working. Good job.

Not sure if it's obvious, I was warned here beforehand.
