### ISSUE TITLE
Can't import save from 0.2.2

### ISSUE THREAD

**Issue by desci** [nroutasuo/level13#135]
**Game version**
0.2.3 and 0.2.4

**Browser**
Chrome (Chromium)

**Description**
Trying to export a save from 0.2.2 and importing on 0.2.3 or 0.2.4 didn't seem to work. Trying to import back into 0.2.2 worked. Did not tried to "upgrade"the game (for example reloading git hub pages).
The 0.2.2 instance is running on a cached git hub pages (chrome offline) and the other versions are being served by tomcat apache and accessed on chrome with "localhost" as address.

**Comment by nroutasuo** [comment]
At this point in development I cannot yet guarantee that saves between versions are compatible. I made some changes between 0.2.2 and 0.2.3 that break old saves in alpha it doesn't really make sense to invest time in converting saves. Once in beta that will be another question, but for now I am closing this issue.

**Comment by desci** [comment]
Just an update: I refreshed the github page and it resets the game.
Looking quickly at the changes involved, I agree there's no sense in the effort to convert the game save. The several "your save may break" messages are enough.
