### ISSUE TITLE
got stuck. enable the cheat system.

### ISSUE THREAD

**Issue by Sijko** [nroutasuo/level13#136]
**Game version**
current

**Browser**
opera

**Description**
i was exploring on level 6 , after updating the browser window i appeared on lvl 5 and there is no way out cause stair up not repaired. used cheat engine to explore all level but theres no camp. please tell me how to enable the cheats to go back on upper levels cause it s really sad to start over. if you want to keep it secret plaease mail me how to enable it. l3na.inv3rs3@gmail.com

**Comment by Brilliand** [comment]
Save game to your local disk.  Edit "config.js" to set isCheatsEnabled to true.

**Comment by nroutasuo** [comment]
In the current (alpha) state of the game updates do unfortunately sometimes break old saves. You can enable cheats as @Brilliand said on a local version. I do not intend to support cheats for the live version.
