### ISSUE TITLE
Can't go on level 4. Area too radioactive.

### ISSUE THREAD

**Issue by SvechAS** [nroutasuo/level13#139]
**Game version**
0.2.4

**Browser**
Chrome

**Description**
Both enters on level 4 need 15 radiation protection, when my maximum radiation protection is 12, I wait long time and get some items from trader.

![Clip2net_190518215244](https://user-images.githubusercontent.com/11705469/57973855-dc174780-79b7-11e9-9ea3-0211f933fd89.png)

**Comment by Brilliand** [comment]
Yeah, 15 radiation protection isn't going to happen on level 4.  With 12 radiation protection, you have the best items possible at that point.

If you could somehow squeeze past level 4, there's a bug that allows the Gas Mask (+15 radiation protection) to be obtained from scavenging on the very next level.

**Comment by mavion** [comment]
+15 radiation protection is possible if you obtain the quality gloves, scrap metal helmet and scrap metal armor. All of these can be obtained from trading without accessing level 3. There's nothing interesting on level 4 though and the passages down from that level can't be built.

**Comment by Brilliand** [comment]
The next level after 4 is 14.  Access to 14 is still barred due to the cement situation, though.

**Comment by Pimhazeveld** [comment]
I managed to reach level 3 from level 4 though. 4 was a very unusual level since the entire place is irradiated and food is not an abundance but level 3 is more normal. Level 3 also contains a bunch of new equipment like a gas mask and a gun.

**Comment by nroutasuo** [comment]
The upcoming version will include some fixes to the radiation balancing as well as a stricter limit to how far down you can explore.
The update after that, I hope, will finally actually unlock more levels.
