### ISSUE TITLE
Movement food cost doesn't match "Back to camp" food cost

### ISSUE THREAD

**Issue by Brilliand** [nroutasuo/level13#140]
**Game version**
Local copy matching commit 967e7e3749a6a9a0f9825fc72f1e5bc6e852b28e

**Browser**
Google Chrome

**Description**
After equipping shoes, I compared the food and water costs of walking back to camp manually vs. pressing the "Back to camp" button.  It appears the shoes are intended to reduce the food and water costs, but due to the way food and water is rounded, I didn't get any actual reduction in food/water costs unless I was moving several spaces in a single bound.

As further support: I experimented with a set of hacked shoes that reduced my movement cost to 0.4, and it reduced my food and water costs to 0 for each step.

I recommend rounding food and water amounts to the nearest 0.1 (instead of to the nearest 1) to avoid this problem.

**Comment by nroutasuo** [comment]
This is an old one, but I've finally fixed it for the upcomind update. The shoes will only affect stamina and not food/water cost in the future.
Thanks for the detailed bug report!
