### ISSUE TITLE
Cannot go on after completing level 4.

### ISSUE THREAD

**Issue by ZinniaZ** [nroutasuo/level13#142]
**Game version**
0.2.4(alpha)

**Browser**
Safari

**Description**
Cannot go on after completing level 4. I cannot get concrete to build an elevator to level 14, and there is no stairs down to level 3.

**Comment by nroutasuo** [comment]
Thanks for reporting. The alpha version blocks progression beyond a certain point on purpose but it's not communicated very well in-game. I'll leave the bug open to remind myself to fix that.

**Comment by nroutasuo** [comment]
There will be a proper notification when you reach the last available level in the next version.
