### ISSUE TITLE
Worn trainers marked as worse than improvised flip-flops

### ISSUE THREAD

**Issue by clapointe** [nroutasuo/level13#143]
v0.2.4
I found some worn trainer shoes and for some reason they appear with the little down-facing arrow, as if the improvised flip-flops were better. If I equip them, the bag tab has the up arrow to show me that a "better" item can be equipped, when it clearly shows that the trainers reduce movement cost by 20% rather than the flip-flop's 10%. 
They work correctly in reducing the cost, it's only a minor display problem.

**Comment by nroutasuo** [comment]
Thanks for reporting! This has already been fixed for the upcoming version.
