### ISSUE TITLE
Holding more than my bag can

### ISSUE THREAD

**Issue by pieninja1** [nroutasuo/level13#146]
![B1A5D3B9-F426-4938-B2E1-9995E7BC2B69](https://user-images.githubusercontent.com/57226470/72004357-13b15900-3200-11ea-8d97-1bda5dd14b32.png)
0.2.4

I fought an enemy and I was able to hold 34/30 on my plastic bag.

**Comment by pieninja1** [comment]
I took the things by clicking on each drop

**Comment by pieninja1** [comment]
I’ve looked at some other closed bug reports and it seems this was an issue before. Also, here is some other information. Version: 0.2.4 Browser: Safari

**Comment by nroutasuo** [comment]
Thanks for the details! This should be fixed in the upcoming update.
