### ISSUE TITLE
Bug of "rest" button

### ISSUE THREAD

**Issue by 1379Post** [nroutasuo/level13#148]
**Game version**
0.2.4（alpha）

**Browser**
Firefox

**Description**
When I return to camp,"rest" botton is always cooling down;
And after it cools down,
when I click "rest" botton, nothing happens.

![bug.PNG](https://i.loli.net/2020/01/20/x8V64mEqyBGUNPZ.png)

![bug2.PNG](https://i.loli.net/2020/01/20/e4jPNvwiEaBz6FU.png)

**Comment by nroutasuo** [comment]
I see you're playing an unsupported version of the game (the Chinese translation). It often includes incomplete features and untested fixes so I'm not sure if this bug really appears in 0.2.4. However it should be fixed in the next official release.
