### ISSUE TITLE
Could there be some leniency with food and water stamina loss?

### ISSUE THREAD

**Issue by ikkonoishi** [nroutasuo/level13#149]
I leave camp with 0 food and water knowing I have 10 of each to collect just outside, but I'm instantly reduced to 125 stamina. Then when returning to camp my bed is still on cooldown for 60 seconds.

Could you maybe lower the max stamina, but leave the current value and have an increase to stamina usage when current stamina is greater than the cap instead?

**Comment by Pimhazeveld** [comment]
I feel like a way to solve this would be to not reduce stamina loss when on a tile that has water and or food to gather while you have none. All your camps are tiles like these by default so heading out with nothing wouldn't reduce it.

**Comment by nroutasuo** [comment]
In the new version which was released today this is fixed but a little differently. You are not instantly set to 125 stamina but instead have some time to react to hunger/thirst, so that if you collect immediately, your stamina is reduced very little if at all.
