### ISSUE TITLE
More common crafting materials?

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#150]
**Game version**
0.25

**Description**
Right now I'm getting really bored with the game. Floor 11 is blocked by polution and I need leather jacket and leather gloves to get more poison protection. Both take leather. Which I do not have.
I have done around 10 loops around floor 12 so far, scavenging on every tile, taking any leather I can find. I only got leather drops 3 times of the ~500 times I've scavenged a tile.

Please make it so leather, hairpins, plastic bottles and other stuff drop often _from enemies_. It'd give me an incentive to bait out encounters and get those materials easier.

**Comment by nroutasuo** [comment]
For the upcoming update, I've added a fallback that gives you more of the ingredients you actually need from scavenging.

In the future I want to make certain enemies drop certain materials.

**Comment by nroutasuo** [comment]
In the next update, enemies will always drop ingredients, and the fallback checking for the ingredients you actually need at the moment applies to them too. That will hopefully solve this problem.
