### ISSUE TITLE
despair 100%?

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#152]
**Game version**
0.25

**Browser**
Chrome

**Description**
It seems like despair has a 100% chance of both losing items and injuring. I've reloaded the page, despaired multiple times (and during different scavenges too) and so far I've lost items every single time. Except once but that may have been because I had no equipment on me.

**Comment by nroutasuo** [comment]
Are you on a level with no camp when despairing? In that case it's intended.

**Comment by CondoSlime** [comment]
If that's the case. Then that's rather rough. Those levels are already extremely difficult to get through as they are. I can't remember the last time I didn't despair when going to another level without a camp because I can either scavenge a very low amount of tiles or a large amount but I choose the quick way out.

**Comment by nroutasuo** [comment]
Agreed, the non-camp levels are very punishing. But I think I'd rather try to make the levels themselves more doable (and interesting) and keep despair as an actual penalty than make despair randomly be nice to the player.
