### ISSUE TITLE
plus on libary upgrade level

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#153]
**Game version**
0.25

**Browser**
Chrome

**Description**
There's a Plus on the upgrade level for the libary building. Dev probably forgot to take it out. This plus is present on other amount buttons as well but they are set to be invisible. 
![WHTJsVJ9ow](https://user-images.githubusercontent.com/10517450/73659887-66632100-4697-11ea-9efb-42459b8b6bd7.png)

**Comment by nroutasuo** [comment]
Have you unlocked Education? It's supposed to signify that the building has been improved by an upgrade. Not the most obvious UI I know.

**Comment by nroutasuo** [comment]
I've improved this in the upcoming version by making these kind of upgrades manual rather than automatic. When an upgrade unlocks a higher level building, you still need to manually improve it rather than that plus sign just magically appearing. Hope it makes this clearer.
