### ISSUE TITLE
Brutal level 9

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#154]
**Game version**
0.25

**Browser**
Chrome

**Description**
Here is my level 9
![EFdbqHDmtd](https://user-images.githubusercontent.com/10517450/73660400-6879af80-4698-11ea-8139-75f16b512bc6.png)
Blue = 35 cold
Red = 5 radiation
I need to have the warm jacket equipped to move in the blue area. That means I can't have enough protection when walking into the red area. Forcing a -75 health penalty on me reducing my stamina to 250 barely allowing me to walk anywhere. Thankfully there's a ladder to the left and hopefully I can get some better equipment in level 8 to traverse this but others may not be as lucky as me.

**Comment by nroutasuo** [comment]
I've improved world generation so this should not happen in the next version. Cold and radiation/pollution won't appear in neighbouring sectors.
