### ISSUE TITLE
+speed = -speed

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#155]
**Game version**
0.25

**Browser**
Chrome

**Description**
Weapons with a +% speed modifier make you attack slower instead.
Comparison: 
![L13 speed comparison](https://user-images.githubusercontent.com/10517450/73681429-9b369e80-46be-11ea-84c9-809dee59ec11.gif)

**Comment by nroutasuo** [comment]
This is actually more of a display issue. The heavy axe is supposed to be slow. I'll fix it for the bugfix update.
