### ISSUE TITLE
Shop thinks crossbow > improved crossbow

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#156]
**Game version**
0.25

**Browser**
Chrome

**Description**
![4GZ1s5wqho](https://user-images.githubusercontent.com/10517450/73759823-c8da2100-476c-11ea-8f82-7cbcfa19c19a.png)
I currently have an improved crossbow equipped (14 damage speed +10% (actually speed -10%)) and the game thinks this crossbow is better. When I open the trade window, it correctly says the crossbow is worse but in this menu it thinks its better.

**Comment by nroutasuo** [comment]
I can't believe I keep getting this one feature wrong. I think I'll refactor the whole item stat thing in the future.

**Comment by nroutasuo** [comment]
Fixed for the next update.
