### ISSUE TITLE
Game considers items equipped as items in your inventory

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#157]
**Game version**
0.25

**Browser**
Chrome

**Description**
![chrome_CbV4jjSUOO](https://user-images.githubusercontent.com/10517450/73785121-fcca3c00-4796-11ea-8f7d-f0cc2e051aea.png)
If you have an item equipped and that same item in your inventory. You can take them both with you on an adventure.
This does not dupe the equipment and going out only took one crossbow with me.

**Comment by nroutasuo** [comment]
Nice catch! Fixed.
