### ISSUE TITLE
Holding a button in the trade window repeatidly repeats the latest action you did.

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#162]
**Game version**
0.25

**Browser**
Chrome

**Description**
I think this is best explained by showing.
![L13 trade glitch](https://user-images.githubusercontent.com/10517450/73969935-91aa7200-491c-11ea-8a54-f2f171253dd8.gif)
Holding a button repeats the latest action constantly. If I add fuel and then hold a button, it'll add fuel constantly. Same goes for removing items.
This is annoying as it also applies to the "accept" button and can result in spending more items than you want.

**Comment by nroutasuo** [comment]
This should be fixed in the current version.
