### ISSUE TITLE
No Concrete?

### ISSUE THREAD

**Issue by aclevel13** [nroutasuo/level13#165]
**Game version**
v.0.2.4.

**Browser**
internet explorer

**Description**
Explored all of levels 4-13. Only way to go up to level 14 is by building an elevator with concrete and metal. Cannot find concrete anywhere, by trading or exploring.

**Comment by nroutasuo** [comment]
You're playing a very old version. In the latest version, you can get concrete. However, level 14 is still locked for now - the features unlocking in are still in development.

**Comment by SoMall-dumpling** [comment]
Maybe you’re playing the Chinese version, which is very old.
