### ISSUE TITLE
The - button lights up despite when number is 0 if assigned through text input

### ISSUE THREAD

**Issue by Unihedro** [nroutasuo/level13#168]
**Game version**v. 0.2.7 (alpha)
(write the version you were playing)

**Browser** Chromium

**Description**
(write what happened, what should have happened, and any context that you think might help fixing the bug)
1. Have all workers assigned as one worker type (e.g. metal.)
2. Using text input, assign some workers into a currently 0 worker type (e.g. rope)
3. The game clears the workers correctly, but now the "-" button is lit up and not reset properly.

Very minor, UI only, no errors in console

**Comment by nroutasuo** [comment]
Thanks for reporting!

**Comment by nroutasuo** [comment]
Fixed for the next update.
