### ISSUE TITLE
mouse-over text box can cause minor flashing effect

### ISSUE THREAD

**Issue by Centritide** [nroutasuo/level13#170]
0.2.7 (alpha)

Chrome Version 83.0.4103.116

This is a minor issue: When mousing over a button low on the screen, for example, an unscouted locale on a tile where a trap/bucket can also be built, the text box extends below the bottom of the page. If the page is scrolled down, then the cursor is moved slightly downwards, the text box disappears, snapping the page down and moving the button under where the cursor is. This causes the text box to reappear, moving the button back up, causing the text box to disappear again. This loop creates a flashing effect.

**Comment by nroutasuo** [comment]
Thanks for reporting!

**Comment by nroutasuo** [comment]
This should be fixed in 0.5.1
