### ISSUE TITLE
Back to camp circumvents hunger/thirst status effects

### ISSUE THREAD

**Issue by BlackCapCoder** [nroutasuo/level13#175]
Imagine we leave camp with 2 food, 2 water and 1000 stamina. We walk 1 tile away from camp and realize we'll be out of food and water after our next move. We wish to return to our camp.

#### Scenario A

We press "back to camp" at the cost of 1 food, 1 water and 10 stamina, which is the cost of walking the distance. Back in camp, our remaining stamina is 980.

#### Scenario B

We walk back towards camp at the cost of 1 food, 1 water and 10 stamina. We are now out of food and water which inflict hunger and thirst- lowering our maximum stamina to 100. As we enter camp, both of the effects are cleared. Our remaining stamina is 100.

### Proposition

I argue that "back to camp" should behave as if we walked back to camp.

B then, is strictly speaking the correct behavior for the "back to camp" button:
we get hungry/thirsty in the rest of the game, but not this one edge case.

However, I don't think B makes sense: we ran out of food as we arrived on
this tile and we ran out because we just ate it. There is more food on this tile.

In my opinion we should allow a grace period of a single scavenge before
giving the player any status effects.

Ran out of food on top of your stockpile? No problem! Grab some more and be on your merry way.

Ran out in the middle of nowhere? Oh oh- you're stuck here until you can scavenge some. You're starving now, hurry up!

**Comment by nroutasuo** [comment]
Good point and good ideas. I have to think about exactly what would be the best way to solve this. I think it also ties into the "rest outside" option which is currently a bit confusing but is meant to solve two similar problems (running out of stamina just a few steps away from camp, and running out of food/water in a sector with traps/buckets and having to just sit there waiting for them to fill up).

**Comment by BlackCapCoder** [comment]
There are two distinct use-cases for stockpiles:

1) Player keeps a few large stockpiles close to camp that serve as production. We want these to slowly replenish over time ala idle games.
2) Player has many small stockpiles scattered all over the map that is used during traversal. Real-time is too slow for a fast-paced playstyle here.

One way to address 2 is to increment buckets/traps by 1 whenever the player moves.

As for running out of food close to base I personally think this is a non-issue. They could and should have planned out their expedition better. I find this part of the game really fun.

**Comment by nroutasuo** [comment]
I've improved this in the upcoming version by making negative stamina effects take some time to go to full effect, so if you collect food/water immediately the end results are the same. Hope this makes sense - would love to get your feedback when the new version goes live in a couple of weeks. Closing the ticket in the meanwhile.
