### ISSUE TITLE
Allow to drop items from bag

### ISSUE THREAD

**Issue by bitmedic** [nroutasuo/level13#178]
When exploring and scavenging, you can reach the situation that you won‘t be able to pickup new water or food as the bag is already full with metal. I‘m aware that you can „manage“ your bag while scavenging, but you can‘t drop items if the scavenge does not drop anything.

Please somehow allow to remove items from the bag at any time.

**Comment by nroutasuo** [comment]
This has been on my to-do list for some time, good to have an official issue for it.

**Comment by nroutasuo** [comment]
I have finally fixed this for the upcoming version 0.5.1. It will go live later this year.
