### ISSUE TITLE
Just a small typo

### ISSUE THREAD

**Issue by SoMall-dumpling** [nroutasuo/level13#179]
**Game version**
v. 0.3.2

**Browser**
Playing on my iPad using the Safari.

**Description**
![IMG_1511](https://user-images.githubusercontent.com/57857764/110117703-359e6f80-7df4-11eb-9ebb-4b0556efa52c.PNG)
"There is a here that seems worth investigating."
"here" is probably a typo. Maybe it should be "library"?

**Comment by nroutasuo** [comment]
Thank you for reporting - has been fixed and will be included in the next update.
