### ISSUE TITLE
Feature request: Add an icon on the map for cell containing food, like it does for water.

### ISSUE THREAD

**Issue by Katorone** [nroutasuo/level13#18]
Feature request: Add an icon on the map for cell containing food, like it does for water.

**Comment by Pimhazeveld** [comment]
Yeah, icons we really need are water, food and water towers. Also really important is if I put buckets or traps there so I know if I'm walking into a "safe zone" where I can refill my water/food.

**Comment by CIH137** [comment]
I feel like the rare stuff like medicine and fuel could help too. I think the place I found fuel was pretty easy to spot but I found medicine once or twice but now I don't remember where it was and I can't mass produce it.

**Comment by Pimhazeveld** [comment]
I thought you could use medicine for making first aid kits but apparantly you can't. The first aid upgrade just does nothing. Also I found my bit of medicine in a silent sewer.

**Comment by nroutasuo** [comment]
You might have noticed that the minimap contains more information than the big level map, including food icons. In any case I agree the level map should also be more informative.

Medicine including first aid kits is a later-game feature and still a work in progress.

**Comment by nroutasuo** [comment]
Version 0.2.3 has an improved map that includes most of these suggestions, so I'm closing this issue. I still like the idea of the half-circle and will hopefully improve the appearance of the map some more in the future.

**Comment by desci** [comment]
Just adding a note for consideration

The information available as text does help, however it is really different when you can see information on many cells at once.

Perhaps it would take another person to redesign the map with a different point of view.

**Comment by nroutasuo** [comment]
Absolutely, I am not abandoning the map just because I'm closing this issue. I know a lot of the UI needs some polish and perhaps as you said, a second pair of eyes. But I think that will be more relevant once the feature set has settled a bit.
