### ISSUE TITLE
Empty export

### ISSUE THREAD

**Issue by tabasavr** [nroutasuo/level13#182]
**Game version**
0.3.2 (alpha)

**Browser**
Firefox 86.0.1 (64-bit)

**Description**
Clicking export opens empty text field. No errors in console.
Don't have chrome installed but everything works fine in edge.

**Comment by RSBat** [comment]
Just checked in a private tab in firefox, starting a new game and exporting it works fine. So maybe something is wrong with my main save.

**Comment by nroutasuo** [comment]
Works for me in Firefox as well. Could you share your world seed? How far in the game are you?

**Comment by RSBat** [comment]
Seed is 8629. I was on level 10 when noticed this, now on level 9.
I might have cleared export field by accident and it seems to break export. Reloading page does not help

**Comment by nroutasuo** [comment]
Old issue but finally figured this out. Fixed for the next version.
