### ISSUE TITLE
Cannot build trap, but map shows orange dot.

### ISSUE THREAD

**Issue by abdavis** [nroutasuo/level13#184]
**Game version**
0.3.2

**Browser**
Brave (chromium based)

**Description**
I can't build traps at a few locations, even though the map shows the small orange indicator there. I have included my export in case it is useful:
[level13 export.txt](https://github.com/nroutasuo/level13/files/6176469/level13.export.txt)

World seed: 6466

**Comment by SoMall-dumpling** [comment]
I don’t think it is a bug. It exists when a sector can collect food/water by scavenging but cannot build trap/water, but I think it is just a reminder that tells you ‘you can collect water here’.

**Comment by nroutasuo** [comment]
As @SoMall-dumpling wrote, the orange dot only means there is food available in that sector, some way or another. But perhaps I can make the distinction clearer when I improve the map in the future.
