### ISSUE TITLE
Game start broken with new version

### ISSUE THREAD

**Issue by DavidDecraene** [nroutasuo/level13#186]
**Game version**
0.3.3 alpha

**Browser**
Chrome

**Description**
I've played before. Decided to restart for the new version. I've been scavenging until my stamina is at 2 on the starting location. Got 2 metal in total, a huge amount of nothing found, and now I'm out of stamina without any other options (no camp etc) but to try and restart the game again...

**Comment by nroutasuo** [comment]
This sounds like two potential issues to me.

1. Bad starting location with not good enough scavenging. If you didn't restart yet, could you share your world seed?

2. Rest outside not appearing. If you run out of stamina and don't have a camp yet, an option to rest outside should eventually appear. Did you not get that?

**Comment by DavidDecraene** [comment]
Sorry for not coming back to you earlier on this.

Console prints:
ConsoleLogger.js:52 In improvement tr without action name: #undefined
ConsoleLogger.js:52 Info callout already generated! id: undefined, scope: body
ConsoleLogger.js:52 no such upgrade: unlock_item_clothing3h

I tried to restart and had it again. I'm on a dark square, no light, 2 stamina left. No option to rest outside.
If I look at localstorage (gamestate) the world seed appears to be 8191
I'm not sure if that is the latest format, because looking at it I see stuff that doesn't appear to something you'd expect when you started new game. Maybe the issue is that I restarted from an older version, and some of that older version data still exists and messes up the new game. I'll try and clear the local application data later...

Here is some of the content (gamestate) it contains:
	
{level: 5, worldSeed: 8191, gameStartTimeStamp: 1516881551888, gamePlayedSeconds: 107466.79960649935,…}
actionCooldownEndTimestamps: {scavenge-13-1.0: 1523014017267, use_in_home: 1526971760499, scavenge-13-1.-1: 1516966660455,…}
actionDurationEndTimestamps: {use_in_home: 1526971580470, use_in_campfire-13-1.0: 1526971607798,…}
foundTradingPartners: [3, 4]
gamePlayedSeconds: 107466.79960649935
gameStartTimeStamp: 1516881551888
isFinished: false
isPaused: false
level: 5
numCamps: 4
numTradePostCamps: 4
numVisitedSectors: 940
uiBagStatus: {,…}
uiStatus: {currentTab: "switch-in", mapVisited: true,…}
unlockedFeatures: {scavenge: true, scout: true, vision: true, camp: true, fight: true, investigate: false, bag: true,…}
worldSeed: 8191 }

**Comment by DavidDecraene** [comment]
Cleared all local application data, tried again.
World seed is 1659. Only entry now is save (encoded data), which is good I assume.
however, again stuck at 2 stamina, only 2 metal found.
still dont see an option to rest.

**Comment by nroutasuo** [comment]
I figured out why the rest option doesn't show up, and it's not very specific conditions either. I'll fix it for the next update. 👍 Will also still need to look at why you find so little metal.

**Comment by rezich** [comment]
Did this ever get fixed? Just discovered this game today and it looks rad & I want to play it, but I had to restart five times until I started in an area with "metal (common)" just to progress. A "rest outside" option never seems to show up.

**Comment by nroutasuo** [comment]
Update frequency on this game is rather low due to it being a personal side-project but it will be fixed in the next update.

**Comment by nroutasuo** [comment]
This should be fixed in the new version which was released today.
