### ISSUE TITLE
I can not go farther into 11 level because pollution is blocking me.

### ISSUE THREAD

**Issue by Snoopy1120** [nroutasuo/level13#187]
v. 0.3.3 (alpha)

Chome

Here is a screenshot
![Screenshot 2021-04-27 1 20 12 PM](https://user-images.githubusercontent.com/83303297/116284686-57183980-a75b-11eb-9591-cfb9f7f570d5.png)
I have done everything i could but i can not do anything now because of the pollution

**Comment by nroutasuo** [comment]
How high is the pollution? Have you managed to get your hands on a leather jacket yet?

**Comment by Snoopy1120** [comment]
5 and yes
i will try with the leather jacket

**Comment by Snoopy1120** [comment]
i put on the leather jacket but didn't work

**Comment by Snoopy1120** [comment]
should i also put on the leather gloves?

**Comment by Snoopy1120** [comment]
ok i got passed it

**Comment by nroutasuo** [comment]
Good, thanks for the update! I'll close this.
