### ISSUE TITLE
How do you trade?

### ISSUE THREAD

**Issue by Snoopy1120** [nroutasuo/level13#188]
**Game version**
(write the version you were playing)

**Description**
(write your suggestion here)

**Comment by nroutasuo** [comment]
Which upgrades have you unlocked? 
Trade between your camps happens automatically when you build trading posts in all of them.
Trade with other factions only becomes available when you unlock the market.

**Comment by nroutasuo** [comment]
Looks like actual trading will unlock for you a little later. But having built trading post in all your camps you should see that their resources (and storage capacity) are combined.
