### ISSUE TITLE
Inventory more then max

### ISSUE THREAD

**Issue by Burgo-admin** [nroutasuo/level13#190]
**Game version**
(0.3.3)

**Browser**
(Safari)

**Description**
(I can leave the camp with over 30 items when 30 is max inventory )

**Comment by nroutasuo** [comment]
Thank you! :) Looking forward to getting it to a beta stage one day.

**Comment by iuriguilherme** [comment]
![image](https://user-images.githubusercontent.com/2027447/150647003-0b960e13-9eaf-434b-af0d-90eb7b1b0bbf.png)

**Comment by nroutasuo** [comment]
This one should be fixed in the upcoming version
