### ISSUE TITLE
Game softlocked

### ISSUE THREAD

**Issue by Bioniclegenius** [nroutasuo/level13#193]
I'm in level 13. Fully explored my map as far as it can go, researched all I can, completely stuck. The edges are too cold for me to progress, and I can't research anything warmer; village is capped out as far as it will allow me, inventory capped, area finished... looks to me like this particular map is softlocked.

[Save.txt](https://github.com/nroutasuo/level13/files/6534512/Save.txt)

**Comment by pieninja12** [comment]
yep i got the same issue 
[Untitled.txt](https://github.com/nroutasuo/level13/files/6546574/Untitled.txt) < my save
there doesnt seem to be any way to progress

**Comment by nroutasuo** [comment]
I added a tool [here](https://nroutasuo.github.io/level13/tools.html) (second "fix" button) where you can fix your save if you have this usse (add Crafting for free). Let me know if that doesn't help!

**Comment by pieninja12** [comment]
it worked, thank you
