### ISSUE TITLE
wrong display of rumors / upgrade

### ISSUE THREAD

**Issue by Chalice12** [nroutasuo/level13#194]
**Game version**
0.3.3

**Browser**
chrome

**Description**
![Screenshot 2021-05-27 8 53 09 AM](https://user-images.githubusercontent.com/84185109/119846818-74fec880-bed8-11eb-9dc0-8f7fcf17c5ca.png)
the cost for the upgrade was 47 rumors, and i supposedly had 47 rumors. but it wouldnt let me purchase the upgrade. once it did it said that i had about 0.2 rumors.

**Comment by nroutasuo** [comment]
Looks like a display / rounding bug. Thanks for reporting!

**Comment by nroutasuo** [comment]
Finally fixed this for the next version.
