### ISSUE TITLE
Water and Food Bug

### ISSUE THREAD

**Issue by Weeflee** [nroutasuo/level13#195]
**Game version**
v. (0.3.3)

**Browser**
https://nroutasuo.github.io/level13/

**Description**
when i go out and don't bring food or water and just collect it from camp to go scavenge it depletes my stamina from 1000 to 254 for some reason but if i bring a bit of food and water from camp then go out to scavenge and collect food/water from camp it does not deplete my stamina

**Comment by nroutasuo** [comment]
This is because between leaving the camp and and picking up food from the collectors you get the hungry and thirsty status effects, which cap max stamina. I agree it's not great in this scenario though and will think of a better approach in the future. There's a related issue / discussion at #175

**Comment by nroutasuo** [comment]
This has been improved in the upcoming version where the hunger/thirst perk takes some time to take effect and reduce your stamina. Thanks for the feedback - closing this ticket now.
