### ISSUE TITLE
gh-pages branch very outdated

### ISSUE THREAD

**Issue by HeinousTugboat** [nroutasuo/level13#2]
It looks like someone [posted your game to reddit](https://www.reddit.com/r/incremental_games/comments/85bw5m/anyone_played_level_13_im_hooked_so_far/), and the gh-pages branch hasn't been updated since August. I would suggest merging master over since the updates fix some important things.

**Comment by nroutasuo** [comment]
Been meaning to update for awhile. I'll try to get a version wrapped up within a couple of days.
