### ISSUE TITLE
Rename the project. The name is distracting.

### ISSUE THREAD

**Issue by BoQsc** [nroutasuo/level13#201]
**Description**
Level 13 is a very distracting name for a game. 
* In-game it really makes no sense and confuses the player to see the label of **level 13** at the beginning of the game.
* In-search-engine it's hard to google for the game.

**Suggestions:** BrowserRPG, JSDarkCity, JSdecay, WebDarkness and others.

**Comment by nroutasuo** [comment]
I have no plans to change the name of the game at this point. Might adjust how it's shown in the UI in the beginning though.
