### ISSUE TITLE
[JS Error] TypeError: null is not an object (evaluating 'this.currentLocationNodes.head.entity')

### ISSUE THREAD

**Issue by SoMall-dumpling** [nroutasuo/level13#214]
Details:
I don’t know what happened.
Today, I clicked into this repository, opened the latest GitHub page, and then this error bar popped out.

Seed: 2435
Position: 13.0.0 (inCamp: false)
Stacktrace:
updateItemStats@http://nroutasuo.github.io/level13/src/game/systems/ui/UIOutHeaderSystem.js:543:94
onGameShown@http://nroutasuo.github.io/level13/src/game/systems/ui/UIOutHeaderSystem.js:808:24
http://nroutasuo.github.io/level13/src/game/GlobalSignals.js:77:20
execute@http://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4616
dispatch@http://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6745
showGame@http://nroutasuo.github.io/level13/src/game/UIFunctions.js:590:43
http://nroutasuo.github.io/level13/src/game/systems/GameManager.js:157:37

**Comment by nroutasuo** [comment]
Thanks for reporting! Were you able to continue afterwards?

**Comment by SoMall-dumpling** [comment]
> Thanks for reporting! Were you able to continue afterwards?

Yeah, just another weird random bug. Everything’s fine after refreshing the page.

**Comment by nroutasuo** [comment]
Added a fix for the upcoming version.
