### ISSUE TITLE
Attacked by somethin

### ISSUE THREAD

**Issue by SoMall-dumpling** [nroutasuo/level13#216]
**Game version**
0.3.3

**Browser**
Safari.

**Description**
I scouted an abandoned sewer.
![7D9D5F6D-3CB6-46C7-8B4E-B474E0133208](https://user-images.githubusercontent.com/57857764/143669120-34ff2b70-df13-4e33-aea2-c1490cd4e307.png)

Then I was attacked by somethin.
I couldn’t press the ‘fight’ button.
The ‘flee’ button could be pressed, and after pressing it everything was working fine.

**Comment by nroutasuo** [comment]
This should be fixed in the new version which was released today.
