### ISSUE TITLE
Disappearing building projects

### ISSUE THREAD

**Issue by SoMall-dumpling** [nroutasuo/level13#218]
**Game version**
0.3.3

**Browser**
Safari.

**Description**
The staircase between level 7 and 8, and the elevator between level 2 and 3 disappeared.
![30DCBCA1-77C9-45C3-AA67-B1494CD703E7](https://user-images.githubusercontent.com/57857764/143766098-5ce13f5b-1ea8-4f98-97ff-0af0c87a874f.png)
 I guess there’s something wrong with the greenhouses.

**Comment by nroutasuo** [comment]
I believe this is fixed in 0.5.2 which just went live.
