### ISSUE TITLE
Beacon Research Bug

### ISSUE THREAD

**Issue by ACorridorWanderer** [nroutasuo/level13#224]
**Game version**
Level 13
0.3.3 alpha.
Browser:
Chrome

Description
I researched Beacons, but apparently, I cannot build a beacon in my camp. 
![Screenshot 2022-01-31 9 18 23 AM](https://user-images.githubusercontent.com/98608138/151812652-3c33e98c-205b-40f9-9be4-896f86175599.png)
![Screenshot 2022-01-31 9 18 33 AM](https://user-images.githubusercontent.com/98608138/151812663-1ace6162-8f34-4902-9383-b987fb18c3f0.png)

**Comment by ACorridorWanderer** [comment]
Sorry, I just realized that you build beacons outside the camp.

**Comment by ACorridorWanderer** [comment]
Yes, I can play this unblocked on my chromebook.

**Comment by nroutasuo** [comment]
Thanks for updating, I'll close this ticket then. But I'll see if I can make it clearer what new researches actually unlock in the future.
