### ISSUE TITLE
USE div from BAG tab malfunction

### ISSUE THREAD

**Issue by iuriguilherme** [nroutasuo/level13#225]
**Game version**
0.3.3

**Browser**
Google Chrome

**Description**
Found a broken appliance while having rejuv shot, used "back to camp" button, the bag inside the camp showed the notification (1) for the disassemble option but the UI kept showing "use rejuv shot" striked out and never gave the "disassemble broken appliance" button.

Had to save and reload page, disassemble, then USE part of the bag tab was empty until I went outside again.

**Comment by iuriguilherme** [comment]
Also that left the game in a state where maximum storage when leaving camp can be overriden.

![image](https://user-images.githubusercontent.com/2027447/151862847-8db40506-8f6c-4ddb-b685-ba394dcc6a10.png)

Attempt to leave camp with that much of items made me lose everything:

![image](https://user-images.githubusercontent.com/2027447/151862969-d836c2e1-d902-468b-b68e-b149634789c4.png)
![image](https://user-images.githubusercontent.com/2027447/151863064-e32fc640-a9b5-45ac-8f17-b67afc45118d.png)

Referencing #220

**Comment by nroutasuo** [comment]
Seems like two separate bugs to me. Thanks for reporting! I'll take a look at some point.

**Comment by iuriguilherme** [comment]
Yes it's two separate bugs. Bringing a broken appliance while having rejuv shot almost always causes the first bug I described. The one I managed to screenshot in this issue is probably unrelated.

**Comment by nroutasuo** [comment]
This should be fixed in the new version which was released today.
