### ISSUE TITLE
Staircase vanished from projects tab

### ISSUE THREAD

**Issue by iuriguilherme** [nroutasuo/level13#226]
**Game version**
0.3.3

**Browser**
Google Chrome

**Description**
Staircase connecting levels 11 and 10 was replaced by new project of staircase (yet unused) connecting levels 8 and 9. Level 11 has no camp.

![image](https://user-images.githubusercontent.com/2027447/151874313-9a88151c-9e2c-45fd-9314-dcf1e175ec97.png)

**Comment by SoMall-dumpling** [comment]
Yeah, I had the same bug in #218 .
And level 11 has no camp. Yes, not every level is suitable for a camp. You can find tips in the log, and also the icon of the level give a hint of the reason.
(If it is a skull sign or a radiation warning symbol, it means that you can’t build a camp on this level)

**Comment by nroutasuo** [comment]
I'll close this ticket since it's a duplicate, but thank you for reporting anyway.
