### ISSUE TITLE
No Escape

### ISSUE THREAD

**Issue by ACorridorWanderer** [nroutasuo/level13#227]
![Screenshot 2022-02-03 5 46 41 PM](https://user-images.githubusercontent.com/98608138/152442027-77bbb068-e5b3-49af-b6fa-ab4e30b0c9a9.png)
**Game version**
0.3.3

**Description**
Personally, I think that you shouldn't be able to lose things that are essential to leaving an area.
I went downwards into level 6 from level 7. I went downwards into a cold area with my parka on, about 30 temp, and went into a toxic area with my leather jacket on. I explored and and lost my parka and now I'm stuck. Now what?

**Comment by Brilliand** [comment]
You should be able to run through the cold area anyway, braving the debuff to get home.  The environmental hazards don't stop you from moving through already-scouted areas, and the stamina loss doesn't matter if you're just trying to get back to camp.

...of course that won't save you if you left some unscouted sectors in the hazardous area, but it doesn't look like you did that.

**Comment by Brilliand** [comment]
Correction: It doesn't actually work the way I described.  (It probably should.)

**Comment by ACorridorWanderer** [comment]
Thanks for the tip.

**Comment by ACorridorWanderer** [comment]
That sounded very blunt. Sorry!

**Comment by Zarioo12** [comment]
Ok so what do you mean by level 6 and 7?

**Comment by nroutasuo** [comment]
It's been awhile but this has been sort of fixed in the current version, where you can break items rather than losing them, and the chance for you to lose an item that you are actually wearing is not 0 but very low. I'm closing this issue now but let me know if you have any feedback on how it works now!
