### ISSUE TITLE
[JS Error] TypeError: playerLevelCamp is null

### ISSUE THREAD

**Issue by AddemUp102** [nroutasuo/level13#233]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]

Seed: 902
Position: 7.6.5 (inCamp: false)
Stacktrace:
moveCurrencyFromBagToCamp@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:23
sendCaravan@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9
performAction@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31
updateNode@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34
update@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10
update@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165
update@https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16
execute@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611
dispatch@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738
tick@https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29

**Comment by nroutasuo** [comment]
This should be fixed in the version that just went live (0.4.2). Let me know if you have any more problems!
