### ISSUE TITLE
[JS Error] TypeError: playerLevelCamp is null

### ISSUE THREAD

**Issue by DDavidDavidson** [nroutasuo/level13#235]
Details:
[Currently in level 9. Waiting for Bucket to fill up before continuing exploration. File appears to be corrupted and reloaded the page returns the same error.]

Seed: 2412
Position: 9.17.-4 (inCamp: false)
Stacktrace:
moveCurrencyFromBagToCamp@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:23
sendCaravan@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9
performAction@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31
updateNode@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34
update@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10
update@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165
update@https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16
execute@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611
dispatch@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738
tick@https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29

**Comment by DDavidDavidson** [comment]
Duplicate error if that's what you mean.

Glad to know I wasn't the only one who got this bug.

**Comment by nroutasuo** [comment]
Yes, I will close this issue just to keep things organized but thank you for reporting regardless! The details here are useful.
