### ISSUE TITLE
Dog Scavenger Follower found but not visible in party despite notification

### ISSUE THREAD

**Issue by MikeSzym** [nroutasuo/level13#236]
**Game version**
0.4.1

**Browser**
Chrome

**Description**
Entered town, there was a visitor, entered and the game promptly dies there

I found dog (+5 backpack) somewhere down, got info that it will await me in the camp. I see notification but its not there and the notification does not disappear

I checked the save file using online decoder - I found the dog under "Recruit" key but was not in "pendingRecruits" or "followers", probably why the notification kept being on

Unfortunately I did not keep save game copy

**Comment by nroutasuo** [comment]
Thanks for reporting!

**Comment by nroutasuo** [comment]
This should be fixed in the version that just went live (0.4.2). Let me know if you have any more problems!
