### ISSUE TITLE
Crash when entering "party" when having a new visitor

### ISSUE THREAD

**Issue by MikeSzym** [nroutasuo/level13#237]
**Game version**
0.4.1

**Browser**
Chrome

**Description**
Entered town, there was a visitor, entered and the game promptly dies there

This might be related to https://github.com/nroutasuo/level13/issues/236

When trying to get the dog from issue 236 Imoved json part from recuitment to followers which gave me the dog

Zipped save here: 
https://imdev.pl/share/8540b284-5797-47a9-9741-12400e62528a/level13-4.zip

Edit:
I copied both followers from Recruit and PendingFollowers to Followers and game is working but obviously shouldnt be that way ;)

**Comment by nroutasuo** [comment]
This should be fixed in the version that just went live (0.4.2). Let me know if you have any more problems!
