### ISSUE TITLE
Try/catch error in UIOutElementsSystem.updateButtonContainer

### ISSUE THREAD

**Issue by HeinousTugboat** [nroutasuo/level13#24]
So, I've been looking through the codebase and I found this tidbit.. I just wanted to let you know that the reason it throws errors is because `this` is actually an instance of `UIOutElementsSystem`, not any sort of element. So when it gets passed to jQuery, it just sort of breaks. I would've submitted a PR to fix it, but I couldn't actually tell what you were trying to do with this line.

https://github.com/nroutasuo/level13/blob/7c6a4ef0147c499356c6f3a29848bdebeeac05cf/src/game/systems/ui/UIOutElementsSystem.js#L140-L146

**Comment by nroutasuo** [comment]
You found some really hacky old code here!  I've cleaned this up in master, thanks for the heads-up.
