### ISSUE TITLE
Game should not auto-save after throwing a crash error and there is no easy way to import a save after error

### ISSUE THREAD

**Issue by MikeSzym** [nroutasuo/level13#243]
**Game version**
0.4.1

**Browser**
Chrome

This is a general issue. If the game crashes (throws error and screen to report) and auto-saves any reload will cause the game to auto-crash on load. Which is very very bad:
1) I can't copy a save file anymore as I can't access it
2) I can't import my save (I make backups every few mins), I can't clear or do anything

What should be happening:
Error screen should give me as a user a chance to either wipe the game or import a save
But most importantly - the game should NOT auto save after encountering an error as it completely screws the player

EDIT: Found via Settings->Developer Tools->Application->LocalStorage->Delete Key. Hardly ideal but works

**Comment by nroutasuo** [comment]
This is a very good point, I'll fix it in the future.
