### ISSUE TITLE
Bag Making 2 -> Automatic Luggage/Hiker's Rucksack research doesn't provide actual item

### ISSUE THREAD

**Issue by MikeSzym** [nroutasuo/level13#245]
**Game version**
0.4.1

**Browser**
Chrome

**Description**
Collected blueprint on level 17, researched but Hiker's Rucksack is not found in the Crafting
[level13.txt](https://github.com/nroutasuo/level13/files/8605593/level13.txt)

**Comment by nroutasuo** [comment]
Thanks for reporting! I'll include a fix for this in the bugfix update soon.

**Comment by nroutasuo** [comment]
Fix is now live. Let me know if you run into any more issues!
