### ISSUE TITLE
[JS Error] TypeError: playerLevelCamp is null

### ISSUE THREAD

**Issue by menyet123** [nroutasuo/level13#247]
Details:
I think my caravan arrived. but im not sure if i was in camp at all. probably not and I was on a different level, not one with a camp

Seed: 7134
Position: 9.9.-10 (inCamp: false)
Stacktrace:
moveCurrencyFromBagToCamp@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:23
sendCaravan@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9
performAction@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31
updateNode@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34
update@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10
update@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165
update@https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16
execute@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611
dispatch@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738
tick@https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29

**Comment by menyet123** [comment]
This broke my game, it says I should reload, but it gives the same error over and over :(

**Comment by nroutasuo** [comment]
This should be fixed in the version that just went live. Let me know if you have any more problems!
