### ISSUE TITLE
Antibiotics description issue - duplicated text

### ISSUE THREAD

**Issue by MikeSzym** [nroutasuo/level13#248]
**Game version**
0.4.2

improved apothecary is doubled in the description. that's it ;) 

<html>
<body>

Rediscovered modern technology for disease prevention and treatment.
improved apothecary, improved apothecary
--

</body>
</html>

**Comment by nroutasuo** [comment]
Thanks for reporting! I think it's actually two different things, the building and the worker. Still, looks silly. :)
