### ISSUE TITLE
Philosophy + the next one (research... something) do not show up in "All upgrades" after research + unknown bonuses

### ISSUE THREAD

**Issue by MikeSzym** [nroutasuo/level13#249]
**Game version**
0.4.2

**Description**
I researched philosophy and it's not on the "All upgrades list"

I also researched the next upgrade (that required philosopy) that said something about "research" but it's not on the list either and it didnt unlock anything new for me

**Comment by nroutasuo** [comment]
Should be fixed for the upcoming version.
