### ISSUE TITLE
[JS Error] TypeError: playerLevelCamp is null

### ISSUE THREAD

**Issue by Phi161803** [nroutasuo/level13#250]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]
Was on floor 9, built a bucket a bit ago but hadn't done anything for a few seconds. Error popped up and prompted a reload, which _seems_ to fix things.

Seed: 5965
Position: 9.-1.-7 (inCamp: false)
Stacktrace:
moveCurrencyFromBagToCamp@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:23
sendCaravan@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9
performAction@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31
updateNode@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34
update@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10
update@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165
update@https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16
execute@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611
dispatch@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738
tick@https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29

**Comment by Phi161803** [comment]
Addendum I didn't notice until I got back to camp: half a dozen completed "Clear Debris" projects got un-completed on floor 10 (my most recent camp)

**Comment by nroutasuo** [comment]
Ae you playing on 0.4.1? This bug should be fixed on 0.4.2 which was released yesterday. The new projects that showed up are related to the update as well - I changed the worldgen a bit so some things show up that weren't there before.

**Comment by nroutasuo** [comment]
I've not been able to reproduce or heard anyone else encountering this so I will close the ticket. Let me know if you still run into problems!
