### ISSUE TITLE
Good Places for Camps

### ISSUE THREAD

**Issue by SoMall-dumpling** [nroutasuo/level13#253]
**Game version**
0.4.2

**Browser**
Chrome

**Description**
4 good places.
![camp question](https://user-images.githubusercontent.com/57857764/166904289-6ceed516-f30e-44fc-9fb5-6e1957a64d65.PNG)
I thought that there were at most 2 on each floor.
Maybe you have changed it?

**Comment by nroutasuo** [comment]
Yep that's been changed. It used to be 2 hard-coded, but that was really tricky for world generation, so I changed it to one main and a few that are derived from it.
