### ISSUE TITLE
Importing a save lowers camp reputation

### ISSUE THREAD

**Issue by zyx-xyzzy** [nroutasuo/level13#259]
**Game version**
0.4.3 (alpha)

**Browser**
Firefox 100.0.2 (64-bit)

**Description**
Loading an imported save reduces all camps' current reputation value by a small amount (around 0.67 each at my current levels of max rep, from the looks of it?), rather than the expected behavior of retaining the reputation values they were at when the save was made (like the autosave does). This can cause your camps to quickly lose and then regain a worker as their reputation refills back to where it was before, which gets quite annoying with multiple floors involved as it resets their assigned jobs.

Attaching an example exported save in case it helps, and screenshots of the before/after of loading it:
[level13 save.txt](https://github.com/nroutasuo/level13/files/8763913/level13.save.txt)
![overview1](https://user-images.githubusercontent.com/106144712/170067850-05503737-522d-4381-9317-e20cb3c5e233.png)
![overview2](https://user-images.githubusercontent.com/106144712/170067935-f9bd6d4b-e9bb-45af-ac6b-90c464c2abed.png)

**Comment by nroutasuo** [comment]
I finally figured out why this happens and fixed it for the next version.
