### ISSUE TITLE
Sit down while resting/recovering

### ISSUE THREAD

**Issue by cimbraien** [nroutasuo/level13#26]
Is it a bug or is that actually allowed?

**Comment by primeprover** [comment]
It certainly is possible.
You can also switch settlements while recovering

**Comment by HeinousTugboat** [comment]
Pretty sure it's a bug since you can't do it the other way around. Sitting down blocks resting, at least, I thought I noticed that last night.On Mar 24, 2018 4:05 AM, primeprover <notifications@github.com> wrote:It certainly is possible.
You can also switch settlements while recovering

**Comment by HeinousTugboat** [comment]
See #17 for switching settlements while recovering.

**Comment by praxiq** [comment]
For that matter, you can rest, and then heal at the hospital while resting, and then sit down while resting and healing - but only in that order!

Personally, I think that allowing these actions simultaneously (in any order) is a good idea. 

_From a logic perspective:_ it says "rest," not "sleep." Presumably you're resting while you're in the hospital. And you can also have a chat around the fire while recovering stamina from a long trip. 

_From a gameplay perspective:_ It's annoying, but tolerable, to have to sit and wait and do nothing while rest and treatment are occurring. Treatment is especially slow. If I had to wait for both, one at a time, it would quickly go from "fun" to "frustrating." And after waiting, I'm eager to get out again - the last thing I want to do is wait yet again, even for a few seconds, to "sit down." Especially just for one measly rumor, when each upgrade can cost dozens or even hundreds of rumors. Being able to "multitask" the real-time elements just makes the game more fun.

**Comment by nroutasuo** [comment]
@praxiq Yes I agree, I definitely intend to allow some simultaneous actions in the camp, the inconsistencies are due to not quite deciding which ones yet.

**Comment by nroutasuo** [comment]
Decided to go for the simple solution for now: Blocked in the next version.

As for having something interesting to do while resting/recovering, I'll just have to make sure there are other things to do in the camp that aren't "busy" actions focused on the player character.
