### ISSUE TITLE
Deleted rumors

### ISSUE THREAD

**Issue by Mr-critic** [nroutasuo/level13#266]
**Game version**
0.4.3

**Browser**
Chrome 

**Description**
When logging back into game it would randomly delete rumors and other resources.

**Comment by nroutasuo** [comment]
Thanks for reporting! One detail: when you say "logging back" do you mean reopening the browser / tab or just coming back after idling?

**Comment by Mr-critic** [comment]
Yes

**Comment by nroutasuo** [comment]
I finally found out why this happened and fixed it for the next version.
