### ISSUE TITLE
Bigger backpack

### ISSUE THREAD

**Issue by MasterCard69** [nroutasuo/level13#269]
**Game version
V0.4.3 (alpha)
**Description**
How do you get a bigger backpack.

**Comment by nroutasuo** [comment]
If you need help with the game, the [discussions page](https://github.com/nroutasuo/level13/discussions), the [subreddit](https://www.reddit.com/r/level13/), or the [discord server](https://discord.gg/BzMbATyKph) better alternatives than issues. Issues are meant for bug reports and feature requests. 

That said, to answer your question - you can find bags when scavenging or scouting, via trade, and eventually better bags also become available to craft (after researching related upgrades).
