### ISSUE TITLE
Switching gear

### ISSUE THREAD

**Issue by primeprover** [nroutasuo/level13#27]
Either it is hidden or it is impossible to switch gear. I discovered sunglasses before a wollen hat and can't work out how to switch.

**Comment by Pimhazeveld** [comment]
Currently the only way to switch is desperating until you lose all your sunglasses.

**Comment by Pudding01** [comment]
And apparently the sunglasses will push the hat out of the head slot if you find them while wearing a woolen hat...

**Comment by nroutasuo** [comment]
Switching gear has been implemented in master and will be in the next update.
