### ISSUE TITLE
Refinery can be re-scouted on the first visit

### ISSUE THREAD

**Issue by yupinov** [nroutasuo/level13#277]
**Game version**
0.4.3

**Browser**
Firefox 110.0.1

**Description**
I discovered a refinery, scouted it once, spent some time on the same street scavenging the fuel, and noticed the scout the refinery button is counting down. I was then able to wait and to scout the refinery again (encountering only 1 bandit). When revisiting the street later, the scout the refinery option isn't there anymore.

This same street had pests blocking the way to the east. Later I cleared out the 3 pests. Yet on the next visit I was also able to fight "1/0" fight again 😶‍🌫️ 
![bild](https://user-images.githubusercontent.com/16647264/224550223-4282c95d-4f61-413d-a25d-56624f641e6e.png)

**Comment by nroutasuo** [comment]
Thanks for reporting!
