### ISSUE TITLE
Missing scavenger

### ISSUE THREAD

**Issue by yupinov** [nroutasuo/level13#278]
**Game version**
0.4.3

**Browser**
Firefox 111.0.1

**Description**
I investigated a building on level 8 and found Dog who would be waiting for me in the camp.
I came there and didn't see it. Could be related to me having 4/4 followers already.

**Comment by yupinov** [comment]
After leaving a spare slot, I did meet it at the camp some time later. So maybe not a bug?

**Comment by nroutasuo** [comment]
Thanks for the report and the update! It should probably be shown better anyway so I'll mark this as a bug and investigate.

**Comment by nroutasuo** [comment]
Should be fixed in 0.5.1
