### ISSUE TITLE
Crash by missing newspaper description.

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#283]
v0.51
Opera GX
I found an item in level 16, upon going to my inventory to look at it, the following error happened.
![image](https://github.com/nroutasuo/level13/assets/10517450/feef5223-8ac6-47cf-9b2b-5b24c5feabf1)

![image](https://github.com/nroutasuo/level13/assets/10517450/2ac9715c-8d32-4ba2-b72a-c058d7232ac6)

**Comment by nroutasuo** [comment]
Thanks for the report!

**Comment by nroutasuo** [comment]
Fixed in 0.5.2
