### ISSUE TITLE
Crash on viewing trader

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#285]
v0.5.1
Opera GX
My game crashed when clicking on the trade window in level 5 while a trader was there.
This is the message that appeared in the console.
![image](https://github.com/nroutasuo/level13/assets/10517450/4251c2d6-ad07-4619-95e0-42938605f3f2)

And here is my current savefile.
[level-13-save.txt](https://github.com/nroutasuo/level13/files/12064878/level-13-save.txt)

**Comment by nroutasuo** [comment]
Fixed in 0.5.2 which just went live.
