### ISSUE TITLE
I got hurt but also not.

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#29]
With the help of the level13 subreddit I made it to level 8 where I lost to a giant spider (harmless btw) It said I got injured but lost no items. I arrived in camp without any injuries or penalty to max stamina.

**Comment by nroutasuo** [comment]
I haven't been able to reproduce this one, and it's quite old, so I am closing the ticket. Let me know if you play the latest version and still encounter any similar issues!
