### ISSUE TITLE
Blocked in by cold areas and don't have enough evidence to unlock wollen hat and mittens

### ISSUE THREAD

**Issue by CIH137** [nroutasuo/level13#3]
I have fully explored the map that I have available and in each direction I hit a cold area blocking the path. Looking at the sample maps, I don't think this is normal.

I tried scavenging for armor and stuff, but it seems pretty hopeless.

Also I'm pretty  sure that is an upgrade to help but currently I am at 450 max storage with a requirement of 525 metal for the next storage upgrade

**Comment by HeinousTugboat** [comment]
Have you emptied out all the sewers? Those give Evidence too, I believe.

**Comment by CIH137** [comment]
I did. I only got 1 blueprint from one and the rest didn't seem to be anything special. I am have 48 and I need 72

![image](https://user-images.githubusercontent.com/27097095/37626472-26a08d8e-2b9e-11e8-8ba3-30deb3555ec3.png)

**Comment by Toksyuryel** [comment]
Hm, seems the real bug here is that you only got 1 blueprint piece before being boxed in. The placement of those should be controlled in such a manner to ensure you can always get enough of them before being boxed in, so that you can build the stairs down and get more evidence.

**Comment by CIH137** [comment]
That makes sense. I know I have been having issues with battling where it freezes up on the continue screen. I guess I wasn't able to pick up the items when I refreshed. I am at 1/3 blueprints, so I think only the first worked right.

**Comment by CIH137** [comment]
Well, I managed to get a tattered shirt and ragged pants which gave me +2 warmth to get to 22 total. I was able to go into the red cold areas and get more evidence. I might still need the blueprints sorted out somehow though to continue. I don't know how all that works in.

**Comment by nroutasuo** [comment]
First of all, thank you for the valuable feedback, but please remember this game is still alpha for a reason so you are likely to run into issues like this.

You should not have had cold areas requiring more warmth than 2 on the first level in the latest version. Can you tell me what cold value you had? (It says something like "It's very cold here ([number])") 

I will recheck the cold levels when looking at the map generation in general next time.

**Comment by CIH137** [comment]
I believe it had a cold value of 30 initially. I would get to the area and it wouldn't let me continue. When I tried to move forward it was grayed out and I couldn't click the button. I think I started with v1.7 and 2.1 seemed to fix whatever was messing up cold value wise.

**Comment by nroutasuo** [comment]
It seems like the main problem here was that cold sectors were blocking you from reaching the locales that contained the blueprints. I've improvement hazard placement a lot recently, also taking blueprint locations into account, so I'm hoping this issue won't pop up anymore in the next version.
