### ISSUE TITLE
No camp on Level 11?

### ISSUE THREAD

**Issue by apuar** [nroutasuo/level13#35]
![](https://raw.githubusercontent.com/apuar/Temp/master/Screenshots/1.jpg)
![](https://raw.githubusercontent.com/apuar/Temp/master/Screenshots/2.jpg)
![](https://raw.githubusercontent.com/apuar/Temp/master/Screenshots/3.jpg)
![](https://raw.githubusercontent.com/apuar/Temp/master/Screenshots/4.jpg)

**Comment by Pimhazeveld** [comment]
Yup. that's a feature.

**Comment by zp4rker** [comment]
@nroutasuo I think you forgot to close this 😛
