### ISSUE TITLE
Impossible to progress to Level 8

### ISSUE THREAD

**Issue by HeinousTugboat** [nroutasuo/level13#36]
So, this is something I've seen a people talking about and I finally took the time to dig into it. Once I realized that the probability space was only 10,000 seeds big, I just threw cycles at it.

Of the 10,000 possible campable level arrangements, exactly 0 of them have 5 camps before ordinal level 6. Unfortunately, since you don't get `upgrade_building_storage1` until ordinal level 7, there's no way to get tribe storage past 3,000 metal. [Reference 1](https://www.reddit.com/r/level13/comments/86pdby/no_camp_on_level_10/), [Reference 2](https://www.reddit.com/r/level13/comments/86pmg3/increasing_storage_cap_beyond_3000/)

I've seen this personally, too. In case you're curious, these are the possible layouts from ordinal 1 on the left to ordinal 20 on the right, with a space meaning that level isn't campable:
```
XXX XXX XXXX X X XXX
XXX XX XX XXX XX XXX
XXXX X X XX XX XXXXX
XXXX X X X X XX XXXX
XXX X X X X X XX XXX
XXXX X X X X X  X XX
XXX X X X X X X  X X
```

Here's the actual source if you want to check it. I literally just copy-pasted the functions out of their respective files. [campable-levels.zip](https://github.com/nroutasuo/level13/files/1849765/campable-levels.zip)

Let me know if we're all just missing something painfully obvious. 😁

**Comment by Pimhazeveld** [comment]
If you want to visit level 8 anyways you can open the console and paste

```
var currentSector = app.cheatSystem.playerLocationNodes.head.entity
currentSector.components.values[4].improvements.Storage.count = 10
```

10 is the number that the amount of storages in the camp on your current level will be changed to.

**Comment by tasonir** [comment]
If I'm reading this correctly, I assume you're marking camps on level 12 down to 0 or 1?  Because I think you always start in a camp tile on level 13.  And then you're saying there's 2 out of 20 layouts that would have no camp on level 12 or 11?  You'd have to reach level 10 to build a second camp?  I don't think that's possible to do - you can't go over 450 storage on only one camp.  Is the level 12 camp guaranteed?

**Comment by HeinousTugboat** [comment]
Ok, so I just realized I made a silly off-by-1 error, but it doesn't change a whole lot. Disregard the first column..

```
XX XX-X XXXX X X XXXX
XX XX- XX XXX XX XXXX
XXX X- X XX XX XXXXXX
XXX X- X X X XX XXXXX
XX X -X X X X XX XXXX
XXX X- X X X X  X XXX
XX X -X X X X X  X XX
```

So, the first X, from left to right, is L13's camp. The second X is L12, then the 3rd space is L11 and so on. The dash is the level 9-8 threshold. Each row is a different possible layout. So L13 and L12 are guaranteed on every layout. Then either L11 or L10 are missing. That's where the issue is, since you can't get past 3000 metal on L9, which requires at least 5 camps. And yeah, there are 2 potential layouts that only have 3 camps at that barrier which are even more hamstrung. I can get actual proportions of the 10k seeds later tonight if anyone's interested. It's pretty easy to check every one.

Sorry for the confusion!

**Comment by nroutasuo** [comment]
This is really impressive, but the only thing you are missing is that the balancing isn't even supposed to work beyond this point. I've pulled all these numbers pretty much out of thin air at this point. The game isn't ready.

The fix will be to eventually implement level progression properly, which I will do once I have all the major features affecting that in place.

**Comment by Pimhazeveld** [comment]
Are you planning on eventually down in the deeper levels (level 2, level 1) put 2 levels in a row where you can't make a camp? I'm sure that would be a great end-game challenge.

**Comment by bummelbirne** [comment]
I´m now on lvl 9 and game has stopped because there is nothing more to do. "sad"

**Comment by apuar** [comment]
got same problem,becouse no camp on level 11 ,so the capsity of resoures only 3000,but  downto level 8 need 3200 metal . :(

**Comment by nroutasuo** [comment]
The balancing has now been adjusted so that you should never get stuck because of this particular problem anymore (storage capacity vs passage cost). This will be included in the next update.

However another blocker is still in place until the latter levels are working in general blocking you from progressing beyond a certain point.
