### ISSUE TITLE
UIOutPopupInnSystem: Selector typo

### ISSUE THREAD

**Issue by HeinousTugboat** [nroutasuo/level13#37]
https://github.com/nroutasuo/level13/blob/ac9bdf732ee80ca99608b2e10138d75b9af4b02e/src/game/systems/ui/UIOutPopupInnSystem.js#L29

`$("inn-popup")` will never exist. Should probably be `$("#inn-popup")`.

**Comment by nroutasuo** [comment]
Fixed, thanks for pointing it out!
