### ISSUE TITLE
Population gone negative and still losing population every few seconds

### ISSUE THREAD

**Issue by druzil** [nroutasuo/level13#38]
just discovered electric light and libraries... 
left the game running overnight, came back the next day and my population in both camps -552 and -500 and still inhabitants are leaving and making the population more negative

**Comment by druzil** [comment]
When I came back to the game it was already very negative, so can't tell if the initial exodus was caused by lack of water.  Certainly there was no water when I came back to the game, but there were no workers to gather water also.

**Comment by Pimhazeveld** [comment]
I just came back to my camp. Even though I certainly had 1000+ food when I left and am gaining 0.13 per second after I came back after a while I only had 213. My water somehow remained at the cap though.

**Comment by foodforarabbit** [comment]
How is your reputation? When my population is too high, the chance of attack is high as well and you need fortifications to reduce that.

**Comment by nroutasuo** [comment]
From @FluffyFoxOverlord at #47 
> I was at the second camp on level 12. And I left the game on overnight and the population was in the negatives the next day. I had 20 population at camp 12 and 16 population at camp 13. My reputation at the time was 15ish% and now it is 25%. Also if I am not at either camp 13 or 12, then population continues to decrease. If I stay at those camps it goes up. As of right now the population is -2/20 for camp 12 and -3/20 at camp 13. However it will not increase more than that, it keeps saying that an inhabitant has left the city and then instantly says that a stranger has shown up.

**Comment by nroutasuo** [comment]
I think this is already fixed in the current version, at least I have not been able to reproduce anymore.
