### ISSUE TITLE
Add import/export

### ISSUE THREAD

**Issue by HeinousTugboat** [nroutasuo/level13#4]
I'm not sure how you're wanting to approach import and export, but it'd probably be useful sooner than later to help debug issues. I know one of my runs my L12 entrance was physically disconnected from the remainder of the floor preventing me from progressing at all. It seems like the map generation might need some prodding.

**Comment by nroutasuo** [comment]
Yes, this is definitely on my to-do list

**Comment by nroutasuo** [comment]
Import/export save has been added and will be in the next update.
