### ISSUE TITLE
negative population

### ISSUE THREAD

**Issue by FluffyFoxOverlord** [nroutasuo/level13#47]
The population becomes negative and I can't seem to get it back up.

**Comment by nroutasuo** [comment]
Could you describe where you were in the game when it went negative? How much population did you have? What was / is your reputation?

**Comment by FluffyFoxOverlord** [comment]
I was at the second camp on level 12. And I left the game on overnight and the population was in the negatives the next day. I had 20 population at camp 12 and 16 population at camp 13. My reputation at the time was 15ish% and now it is 25%.

**Comment by nroutasuo** [comment]
Thanks for the details! Sounds a lot like #38 so I'll close this and add your comment there.
