### ISSUE TITLE
Movement directions incorrect after restart

### ISSUE THREAD

**Issue by EdwardMcCants** [nroutasuo/level13#49]
**Game version**
0.2.2 (alpha)

**Browser**
Firefox Quantum 61.0.1 (64-bit)

**Description**
I started a game, got to the point where I could see movement directions.  Then I restarted.  When I got to the point where I could move again, the active direction buttons corresponded to the previous map, not the current one.  Reloading the page fixed this.  This happened several times for me.

**Comment by nroutasuo** [comment]
Seems like a few (visual) things that should reset don't when you restart. Thanks for reporting!

**Comment by nroutasuo** [comment]
Finally fixed this for the upcoming update.
