### ISSUE TITLE
Multiple injuries on death.

### ISSUE THREAD

**Issue by Nepeneny** [nroutasuo/level13#5]
https://imgur.com/a/97SEG

On the second level, died from a lack of energy to return home, got a lot of head injuries on the way back. Can't heal them. Tried using a medkit, only healed one. Can't progress any more.

**Comment by Toksyuryel** [comment]
Any insight into why it won't let you use treatment? That's supposed to heal all injuries.

**Comment by Nepeneny** [comment]
https://imgur.com/a/8Itly

Because I am injured, apparently.

**Comment by nroutasuo** [comment]
There is a hard cap on the number of injuries you can have and that is definitely way past it.

**Comment by Nepeneny** [comment]
I noticed I also don't seem to be able to create field medicine. Should there be some way to do so? I bought the second medical upgrade.

**Comment by nroutasuo** [comment]
If you mean first-aid kits those are for much later game and a work in progress

**Comment by Nepeneny** [comment]
Ah ok, they're not activated yet? Oh well. Was hoping for some way to progress on.
