### ISSUE TITLE
bar cooldowns are strange

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#50]
**Game version**
v0.2.2 aplha

**Browser**
Chrome version 68

**Description**
The cooldown bar for gathering resources has a strange cooldown which does not help indicate how long I need to wait. Here is a gif of how it looks. I've written an AHK script that shows whenever I clicked which seems to occasionally affect the loading bar [https://i.imgur.com/0kqrlkM.gifv](url)

**Comment by nroutasuo** [comment]
I've seen this but haven't found a good fix / repro yet. I'll keep investigating. Thanks for reporting!

**Comment by nroutasuo** [comment]
Fixed by the linked PR, at least for Chrome and Firefox.
