### ISSUE TITLE
Bug: Pressing enter during scavenging softlocks the game.

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#52]
**Game version**
0.2.2

**Browser**
Chrome 68

**Description**
pressing enter during scavenging brings up another bugged menu which you can't close other than reloading the game. this softlocking you. This might be present with other windows as well

**Comment by nroutasuo** [comment]
Nice find

**Comment by nroutasuo** [comment]
Fixed. Will be included in the next update.
