### ISSUE TITLE
Bug: Resources stolen in raids aren't reported accurately

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#56]
**Game version**
v. 0.2.2

**Browser**
Firefox

**Description**
Raids steal a lot more resources than they claim too. The description will say something like "Raid over. We lost 24 metal", but my stockpile of metal will decrease by a few hundred.

**Comment by mavion** [comment]
I think I found the cause.
In line 99 of /src/game/OccurrenceFunctions.js the code is:

campResources.setResource(name, campAmount - lostAmount);

However campAmount is defined on line 96 and is:

var campAmount = campResources.getResource(name) * amountFactor;

where amountFactor is the number of camps inversed.

So in my case what's happening is that I have 4 camps any resource raided gets set to (25% of max - the lost amount).

**Comment by nroutasuo** [comment]
Thanks for the details, I'll get this fixed soon!

**Comment by nroutasuo** [comment]
Fixed for the next update exactly as you described. Thanks again!
