### ISSUE TITLE
Bug: All raids succeed regardless of defences

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#57]
**Game version**
V. 0.2.2

**Browser**
Firefox

**Description**
All raids succeed. For the player to win a raid the RaidDanger needs to be below 0 and the function only returns positive numbers. I'm uncertain if this is actually a bug or intended, but combined with issue #56 it makes raids quite brutal.

**Comment by nroutasuo** [comment]
Definitely a bug

**Comment by nroutasuo** [comment]
This should be fixed in the upcoming update. Thanks for reporting!
