### ISSUE TITLE
I Unlocked ulban hellculture but didn't unlock a new building.

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#58]
**Game version**
0.2.2

**Browser**
Chrome 68

**Description**
I assembled the blueprint. Then unlocked it in the upgrade screen and afterwards bought it with evidence but no new building showed up. Reloading the game or moving camps did anything.

EDIT: The building farm only appeared after I found the refinery. Collectng fuel made the button appear. I think it should be a bit more clear that you've unlocked something when researching urban hellculture.

As a sidenote. My hospitals always show that I have 0 of them even though I built one.

**Comment by nroutasuo** [comment]
Yes, the button is hidden until all the required resources are unlocked. Might not be the best approach. I'll make a separare ticket for the hospital just to keep track of distinct bugs.

**Comment by nroutasuo** [comment]
Issue with the farm not appearing fixed for the next update.
