### ISSUE TITLE
recruiting when party full causes error

### ISSUE THREAD

**Issue by cookiedan42** [nroutasuo/level13#59]
**Game version**
0.2.2 alpha

**Browser**
chrome

**Description**
when party has 1/1 members, opening recruit option in the inn then clicking cancel gives  error message

ERROR
You've found a bug! Please reload the page to continue playing.

You can also help the developer by reporting the problem on Github.

**Comment by nroutasuo** [comment]
Thank you for reporting!

**Comment by nroutasuo** [comment]
This will be fixed in the next update.
