### ISSUE TITLE
Not sure if it is a bug but I got 2 sewers in one square

### ISSUE THREAD

**Issue by CIH137** [nroutasuo/level13#6]
I was on level 12 and Just happened to come across one area with 2 sewers. I just thought it was a littler weird. I haven't explored either yet, but I'll edit if It acts weird.

![image](https://user-images.githubusercontent.com/27097095/37682524-d6250640-2c57-11e8-9bc3-f42bb92d15fa.png)

**Comment by CIH137** [comment]
They act as separate sewers, so that's nice.

![image](https://user-images.githubusercontent.com/27097095/37682825-9de8948a-2c58-11e8-9eb3-0eb30b2975e6.png)

**Comment by nroutasuo** [comment]
Yes this is as intended.
