### ISSUE TITLE
Sent caravans are lost when reloading the game

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#62]
**Game version**
0.2.2

**Browser**
chrome 68

**Description**
As a sidenote. I would like it if there was a way to see how long it takes for the caravan to reach its destination.

**Comment by nroutasuo** [comment]
The bug is fixed for the upcoming version so I'll close this ticket for now.
The UI improvement is somewhere on my to-do list and will definitely be implemented later.
