### ISSUE TITLE
followers do not give bonusses

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#64]
**Game version**
0.2.2

**Browser**
chrome 68

**Description**
I should have 11 attack here but I got 5 right now. It seems that its not only a visual bug and I actually dont get the extra attack. [https://i.imgur.com/aka8mo4.png](url)

**Comment by Pimhazeveld** [comment]
darn. I'm getting stuck due to this bug. On floor 8 basically every blockade has vampire bats which are 9/4. I can't beat those when my stats are at 5/6 and I'm completely surrounded so I can't progress further.

I was able to find a stairwell in the limited area that I have but how will that help me if there's likely not gonna be a camp to build on F7

**Comment by nroutasuo** [comment]
Fixed! This was caused by the fact that followers are "items" but you can't "equip" them..
