### ISSUE TITLE
Item comparison does not fully work

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#70]
**Game version**
0.2.2

**Browser**
chrome 68

**Description**
The description thinks that improvised flip flops (-10% movement cost) is better than worn trainers (-20% cost). I've also seen cases during trading where the calculation thinks a spear is just as good as a shiv.

**Comment by nroutasuo** [comment]
Fixed for shoes, couldn't reproduce for other item types. I'll close this but keep an eye on item comparisons.
