### ISSUE TITLE
Breaking bug with refineries

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#71]
**Game version**
0.2.2

**Browser**
chrome 68

**Description**
Fleeing from a battle in a refinery automatically clears the refinery without unlocking the workers for it. You can not scout the refinery again meaning you can't use chemists at all for the camp on that level.

**Comment by nroutasuo** [comment]
That's bad! Thank you for reporting.

**Comment by nroutasuo** [comment]
Fixed! Main issue was the button cooldown not being displayed properly (as fleeing also triggers action cooldown).
