### ISSUE TITLE
Bug: Collecting new blueprints while there is already a completed (but unclaimed) set may lead to stacking 3/3 into 4/3

### ISSUE THREAD

**Issue by Unihedro** [nroutasuo/level13#74]
**Game version**
(write the version you were playing)
2.2 alpha

**Browser**
(write down which browser you are using)
chromium 65.0.3325.181 lnx ubuntu 14.04

**Description**
(write what happened, what should have happened, and any context that you think might help fixing the bug)
Bug: Collecting new blueprints while there is already a completed (but unclaimed) set may lead to stacking 3/3 into 4/3
and when crafting, all 4 are lost

**Comment by Brilliand** [comment]
I'm also seeing this while scavenging now (when I've scouted every special location on the map, but haven't claimed the last blueprint yet).

**Comment by nroutasuo** [comment]
This should be fixed in the upcoming version.
