### ISSUE TITLE
Bug: Caravans don't work

### ISSUE THREAD

**Issue by Unihedro** [nroutasuo/level13#75]
**Game version**
(write the version you were playing)
alpha2.2
**Browser**
(write down which browser you are using)

chromium 65.0.3325.181 lnx ubuntu 14.04
**Description**
(write what happened, what should have happened, and any context that you think might help fixing the bug)
Bug: Caravans don't work
"WARN: Unknown resource name: null (ResourcesVO.js:109)" is logged twice in the console when I dispatch a caravan, but nothing happens when they return - LogConstants.MSG_ID_START_SEND_CAMP is also never logged to leftbar

**Comment by nroutasuo** [comment]
This also now fixed for the upcoming version. Thanks for reporting!
