### ISSUE TITLE
Bug : Frequent invalid gathering option

### ISSUE THREAD

**Issue by darkmir** [nroutasuo/level13#77]
**Game version**
0.2.2 (alpha)

**Browser**
(Chrome 68.0.3440.106)

**Description**
(When I click another step, I find the gathering option is grey and invalid which indicates full of water)

**Comment by nroutasuo** [comment]
Was your bag full? This seems related to #53

**Comment by nroutasuo** [comment]
Ok thanks for the details, I'll look into it!

**Comment by nroutasuo** [comment]
UI updates are still a problem in general, my initial approach to them was terrible and I'm slowly fixing that. This particular issue should be fixed in the next update though!
