### ISSUE TITLE
Fight button is disappeared

### ISSUE THREAD

**Issue by Kuroiteiken** [nroutasuo/level13#92]
**Game version**
latest 0.2.2

**Browser**
Chrome

**Description**
Fight button is disappearing and some errors at console. Game first become laggy, then this happened.

![image](https://user-images.githubusercontent.com/882130/50415644-35c27e00-082d-11e9-80ce-c5e6fd3b2c8b.png)

**Comment by nroutasuo** [comment]
I think I've finally fixed this one. Fix will be in the next update. Thanks for reporting!
