### ISSUE TITLE
Upgrades disappearing

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#97]
**Game version**
v. 0.2.3 (alpha)

**Browser**
Mozilla Firefox

**Description**
After unlocking the blueprint for bridges I researched it. When I researched it the option for researching spears disappeared. I do not have the ability to build spears.
It would appear that the same bug also happened with libraries. At the very least I unlocked the blueprint earlier, but do not have the option to research it. Though I did not notice when or if something happened at that point.

**Comment by nroutasuo** [comment]
Someone on Reddit reported something similar with Urban Heliculture. Do you have an exported save for when this happened, and if yes, could you share it?

**Comment by mavion** [comment]
https://pastebin.com/AnSECzf3
It happened in this save, but not at this exact moment.

**Comment by nroutasuo** [comment]
I found a fix and it will be included in the next bugfix release I plan to do quite soon. I also added a fallback so that if you continue this save on the new version you should find the blueprints you missed out on because of the bug by scavenging instead. Thanks for the details!
