### ISSUE TITLE
Recruiting at inn creates duplicates

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#99]
**Game version**
v. 0.2.3 (alpha)

**Browser**
Mozilla Firefox

**Description**
Sometimes when I recruit followers at the inn I get duplicates. It has happened twice so far, and both times happened when I dismissed a follower(or more) first. Both times the number of duplicates matched the attack stat of the follower.
After refreshing I have not been able to replicate this.

**Comment by nroutasuo** [comment]
This seems like a duplicate of #114 so I will close this but definitely look into fixing the bug eventually.
